r"""What may still be **growing** into a URL at a buffer's end, behind the output guardrail
(ADR-0015).
"""

import re

from cortex_core.url_identity import DOT_WORD
from cortex_core.url_spellings import (
    AUTHORITY_SEPS,
    CHUNK_INNER,
    CLOSE_BRACKET,
    COLON_SPELLING,
    DOT_TOKENS,
    GAP_WHITESPACE,
    OPAQUE_SEPS,
    OPEN_BRACKET,
    SOLIDUS_SPELLING,
)
from cortex_core.urls import (
    ARRIVING_AUTHORITY,
    AUTHORITY_WORDS,
    HOST_CHAR,
    OPAQUE_SEP_RE,
    OPAQUE_WORDS,
    SPLIT_GAP,
    SPLIT_LABEL,
    URL_RE,
)

# Every scheme word, for the open-chunk check below. Derived from the same tables as `URL_RE`, so
# the two cannot drift.
_SCHEME_WORDS = AUTHORITY_WORDS + OPAQUE_WORDS + ("data",)

_SCHEME_PREFIXES = (
    tuple(w + s for w in AUTHORITY_WORDS for s in AUTHORITY_SEPS)
    + tuple(w + s for w in OPAQUE_WORDS for s in OPAQUE_SEPS)
    + tuple("data" + s for s in OPAQUE_SEPS)
)

# The longest string that is a prefix of a scheme+separator but not yet a URL match
# ("https://" needs one more character to match URL_RE). It is the stream filter's hold-back bound.
_LONGEST_OPEN_PREFIX = max(len(prefix) for prefix in _SCHEME_PREFIXES)

_UNFINISHED_ENTITY = r"&[#0-9a-z]*"

_OPEN_SEP_RE = re.compile(
    rf"\b(?:{'|'.join(_SCHEME_WORDS)})"
    rf"(?:{OPEN_BRACKET}{CHUNK_INNER}*"
    rf"|(?:{OPAQUE_SEP_RE}){SOLIDUS_SPELLING}?{HOST_CHAR}*"
    rf"|(?:{COLON_SPELLING}|{SOLIDUS_SPELLING})*(?:{_UNFINISHED_ENTITY})?)\Z",
    re.IGNORECASE,
)


def _prefixes(token: str) -> str:
    """Every prefix of ``token``, the empty one and the whole included, as one regex fragment.

    Generated by nesting one optional group per character rather than by listing the prefixes,
    so a token's partial forms cannot drift from the token (`dot` gives ``d``, ``do``, ``dot``).
    """
    return "".join(f"(?:{re.escape(char)}" for char in token) + ")?" * len(token)


_ARRIVING_GAP = (
    rf"{GAP_WHITESPACE}+(?:{'|'.join(_prefixes(token) for token in DOT_TOKENS)}"
    rf"|{_UNFINISHED_ENTITY}|{OPEN_BRACKET}(?:{_prefixes(DOT_WORD)}|\.)?{CLOSE_BRACKET}?)"
    rf"{GAP_WHITESPACE}*"
)

_ARRIVING_SPLIT_HOST = re.compile(
    rf"\b{ARRIVING_AUTHORITY}{SPLIT_LABEL}(?:{SPLIT_GAP})*{_ARRIVING_GAP}\Z", re.IGNORECASE
)


def held_from(buf: str) -> int:
    """The index from which ``buf`` may still be growing a URL. Everything before is final."""
    last = None
    for match in URL_RE.finditer(buf):
        last = match
    if last is not None and last.end() == len(buf):
        return last.start()
    open_gap = _ARRIVING_SPLIT_HOST.search(buf)
    if open_gap is not None:
        return open_gap.start()
    open_sep = _OPEN_SEP_RE.search(buf)
    if open_sep is not None:
        return open_sep.start()
    lower = buf.lower()
    for size in range(min(len(buf), _LONGEST_OPEN_PREFIX), 0, -1):
        suffix = lower[-size:]
        if any(prefix.startswith(suffix) for prefix in _SCHEME_PREFIXES):
            return len(buf) - size
    return len(buf)
