r"""What may still be **growing** into a URL at a buffer's end, behind the output guardrail
(ADR-0015).

Split from ``urls.py`` (which owns the grammar: what counts as a clickable URL in finished text) at
the line cap as the sixteenth addendum landed, the third such split after ``url_identity`` and
``url_spellings``. This module answers the streaming half of the same question. The redactor scrubs
one delta at a time, so it needs an index from which the buffer might still change meaning: release
everything before it, carry everything from it into the next delta. Getting that wrong leaks a link
in pieces, which is why every widening of the grammar has had to be asked whether it opens a shape
that is *not yet* a match and *not yet* a prefix of one either.

Four shapes are open, and all four are bounded: a ``URL_RE`` match touching the buffer's end, a
dotless host trailed by a gap that has opened but not closed (``hxxp://evil dot ``), a scheme word
whose separator or host has not arrived yet (``http[&#58;``, ``https:evil.``), and a trailing
prefix of any scheme+separator the tables enumerate. Carrying is not redacting: the text is
released whole and in order by a later ``feed`` or the ``flush``, so prose that never becomes a
host reaches the user unchanged and only its arrival moves.

Deterministic and dependency-free (stdlib only). Pure state- and I/O-free.
"""

import re

from cortex_core.url_identity import DOT_WORD
from cortex_core.url_removals import REMOVED, REMOVED_RUN, permeable, strip_removed
from cortex_core.url_spellings import (
    AUTHORITY_SEPS,
    CHUNK_INNER,
    CLOSE_BRACKET,
    COLON_SPELLING,
    DOT_TOKENS,
    GAP_WHITESPACE,
    OPAQUE_SEPS,
    OPEN_BRACKET,
    SOLIDUS_SPELLING,
)
from cortex_core.urls import (
    ARRIVING_AUTHORITY,
    AUTHORITY_WORDS,
    HOST_CHAR,
    OPAQUE_SEP_RE,
    OPAQUE_WORDS,
    SPLIT_GAP,
    SPLIT_LABEL,
    URL_RE,
)

# Every scheme word, for the open-chunk check below. Derived from the same tables as `URL_RE`, so
# the two cannot drift.
_SCHEME_WORDS = AUTHORITY_WORDS + OPAQUE_WORDS + ("data",)

# Every plain/defanged scheme opening, derived from the same families as `URL_RE` (the `data:`
# openings included, so a `data:` split across deltas is carried too). The hold-back carries a
# trailing prefix of any of these so a scheme split across deltas is not leaked (`held_from`).
# Sharing the table with the matcher makes drift structurally impossible.
_SCHEME_PREFIXES = (
    tuple(w + s for w in AUTHORITY_WORDS for s in AUTHORITY_SEPS)
    + tuple(w + s for w in OPAQUE_WORDS for s in OPAQUE_SEPS)
    + tuple("data" + s for s in OPAQUE_SEPS)
)

# The longest string that is a prefix of a scheme+separator but not yet a URL match
# ("https://" needs one more character to match URL_RE). It is the stream filter's hold-back bound.
_LONGEST_OPEN_PREFIX = max(len(prefix) for prefix in _SCHEME_PREFIXES)

# An entity reference that has begun but not finished at the buffer's end (`&`, `&#`, `&#5`,
# `&#x3`, `&col`). The leading `&` is load bearing: it is what stops this from holding back every
# scheme word followed by ordinary letters (`database`), and the run it opens is bounded by the
# first character no reference can contain.
_UNFINISHED_ENTITY = r"&[#0-9a-z]*"

# A scheme word whose separator or host is still **arriving** at the buffer's end, in the shapes too
# variable-length to enumerate into `_SCHEME_PREFIXES`: an open bracket chunk (`http[&#58;`), a run
# of separator characters ending in an unfinished entity (`https&#5`, `https&#58;&#4`), and a
# slashless authority whose host has not yet reached its dot (`https:evil.`), which is not a match
# yet and is a prefix of no separator either. Without these the buffer would match no URL, hold
# nothing, and leak the pieces of an opening split across deltas (ADR-0015 seventh + ninth +
# eleventh addenda). All are bounded: the bracket branch by the bracket-free inner run, the entity
# one by the separator spellings, and the host one by the whitespace no authority character is. The
# host branch requires the colon before it, which is what keeps it from holding `database`.
_OPEN_SEP_RE = re.compile(
    rf"\b(?:{'|'.join(permeable(word) for word in _SCHEME_WORDS)}){REMOVED_RUN}"
    rf"(?:{OPEN_BRACKET}{CHUNK_INNER}*"
    rf"|(?:{OPAQUE_SEP_RE}){SOLIDUS_SPELLING}?{HOST_CHAR}*"
    rf"|(?:{COLON_SPELLING}|{SOLIDUS_SPELLING})*(?:{_UNFINISHED_ENTITY})?)\Z",
    re.IGNORECASE,
)


def _prefixes(token: str) -> str:
    """Every prefix of ``token``, the empty one and the whole included, as one regex fragment.

    Generated by nesting one optional group per character rather than by listing the prefixes,
    so a token's partial forms cannot drift from the token (`dot` gives ``d``, ``do``, ``dot``).
    """
    return "".join(f"(?:{re.escape(char)}{REMOVED_RUN}" for char in token) + ")?" * len(token)


# A gap that has **opened but not closed** at the buffer's end: its whitespace, then at most a
# prefix of one dot token, then at most the whitespace that would close it. Every token comes from
# `DOT_TOKENS`, so the hold-back and the grammar cannot disagree about what a gap may hold; the
# bracket forms and the unfinished entity are the two shapes that table cannot carry as text.
_ARRIVING_GAP = (
    rf"{GAP_WHITESPACE}+(?:{'|'.join(_prefixes(token) for token in DOT_TOKENS)}"
    rf"|{_UNFINISHED_ENTITY}|{OPEN_BRACKET}(?:{_prefixes(DOT_WORD)}|\.)?{CLOSE_BRACKET}?)"
    rf"{GAP_WHITESPACE}*"
)

# A **whitespace-split host still arriving** at the buffer's end (`hxxp://evil `, `… evil do`,
# `… evil dot `, `… evil [do`). None of those is a match and none is a prefix of any scheme, so
# without this branch the released text would leak the head of a split host one delta before its
# gap closed. It carries the grammar's own constraint rather than merely looking for trailing
# whitespace: the labels so far must be **dotless**, because only a dotless host can still grow a
# gap. That is what keeps the branch off the common case, an ordinary link followed by a space
# (`https://evil.example/report `), which a gap can never join and which is released as before.
# The authority it opens with wears the **arriving** host anchor, since the slashless form reaches
# its host through a lookahead that a half-typed split host cannot yet satisfy: `https:evil dot `
# would otherwise be released one delta before its own gap closed (ADR-0015 sixteenth addendum).
_ARRIVING_SPLIT_HOST = re.compile(
    rf"\b{ARRIVING_AUTHORITY}{SPLIT_LABEL}(?:{SPLIT_GAP})*{_ARRIVING_GAP}\Z", re.IGNORECASE
)


def held_from(buf: str) -> int:
    """The index from which ``buf`` may still be growing a URL. Everything before is final.

    Four open cases: a URL match touching the buffer's end (the next chunk may extend it), a
    dotless host trailed by a gap that has opened but not closed (`hxxp://evil dot `, which is not
    a match at all yet, the match having ended before the gap), an unclosed separator or host after
    a scheme word (`http[&#58;`, `https:evil.`, neither a match either), and a trailing prefix of a
    scheme ("h" … "https://") not yet matchable. All are carried; anything else cannot change
    meaning with more text.
    """
    last = None
    for match in URL_RE.finditer(buf):
        last = match
    if last is not None and last.end() == len(buf):
        return last.start()
    open_gap = _ARRIVING_SPLIT_HOST.search(buf)
    if open_gap is not None:
        return open_gap.start()
    open_sep = _OPEN_SEP_RE.search(buf)
    if open_sep is not None:
        return open_sep.start()
    open_prefix = _open_prefix(buf)
    return len(buf) if open_prefix is None else open_prefix


def _open_prefix(buf: str) -> int | None:
    """Where the longest suffix of ``buf`` that is a prefix of a scheme opening starts, or None.

    Compared with the removals **dropped**, because a URL parser drops them before it reads the
    scheme at all, so `ht<TAB>t` is the same three characters of `http://` that `htt` is; without
    that a tab landing on a delta boundary released the head of an opening and lost the link
    (ADR-0015 seventeenth addendum). The window is counted in the characters that survive the
    drop rather than in raw ones, so a run of removals cannot push the opening out of reach of the
    scan, and a suffix that is nothing but removals is refused, being a prefix of no scheme.
    """
    size = seen = 0
    while size < len(buf) and seen < _LONGEST_OPEN_PREFIX:
        size += 1
        seen += buf[-size] not in REMOVED
    lower = buf.lower()
    for length in range(size, 0, -1):
        suffix = strip_removed(lower[-length:])
        if suffix and any(prefix.startswith(suffix) for prefix in _SCHEME_PREFIXES):
            return len(buf) - length
    return None
