"""Behaviour of the gate tying the committed Rust stub to the proto it was generated from.

The fixtures below are miniatures of the real pair, and every one of them is written the way
prost really writes it: the escaped bracket, the service banner arriving as a markdown heading
over a collapsed rule, tonic's own doc comment on a client the proto never mentioned. A fixture
inventing its own spelling would test the normalization against itself, so the last test here
pins each of the three against the committed stub, where they are true or the gate is worthless.

The gate's own reason for existing gets a test of its own: a number retuned in the proto and in
nothing else. That is the edit every other gate in this repo watches go past.
"""

from pathlib import Path

import pytest

import protocomments
import stubcheck

REPO_ROOT = Path(__file__).resolve().parents[2]

HEAD = 'syntax = "proto3";\n\npackage cortex.seam.v1;\n'

BODY = """\
// One conversational exchange stream per overlay session.
message CaptureRequest {
  // Longest edge of the returned image, in physical pixels. 0 means "the body's
  // default" (1601).
  uint32 max_edge = 1;
  optional float level = 2; // clamped to [0.0, 1.0]
}
"""

PROTO = HEAD + BODY

STUB = """\
// This file is @generated by prost-build.
/// One conversational exchange stream per overlay session.
pub struct CaptureRequest {
    /// Longest edge of the returned image, in physical pixels. 0 means "the body's
    /// default" (1601).
    pub max_edge: u32,
    /// clamped to \\[0.0, 1.0\\]
    pub level: ::core::option::Option<f32>,
}
impl CaptureRequestClient {
    /// Attempt to create a new client by connecting to a given endpoint.
    pub fn connect() {}
}
"""

BANNER_PROTO = (
    HEAD
    + """\
// ---------------------------------------------------------------------------
// BodyService is hosted by the body (host-native). The brain is the client.
// ---------------------------------------------------------------------------
service BodyService {}
"""
)

BANNER_STUB = """\
/// ---
///
/// ## BodyService is hosted by the body (host-native). The brain is the client.
pub struct BodyServiceClient {}
"""


def _tree(root: Path, proto: str = PROTO, stub: str = STUB) -> Path:
    """Lay a miniature repo out where the gate looks for its two files."""
    for relative, text in ((stubcheck.PROTO, proto), (stubcheck.STUB, stub)):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return root


# ── the rule ───────────────────────────────────────────────────────────────────


def test_a_stub_that_still_says_what_the_proto_says_is_accounted_for(tmp_path: Path) -> None:
    _tree(tmp_path)
    assert stubcheck.check(tmp_path).misses == []


def test_a_number_retuned_in_the_proto_alone_is_reported(tmp_path: Path) -> None:
    """The whole point. Every other gate here watches this edit go past: the constant's own

    registry entry is about the proto comment and the prose around it, and the generated copy of
    that sentence is outside every scan, so the stub goes on stating the old number.
    """
    _tree(tmp_path, proto=PROTO.replace("(1601)", "(1602)"))
    misses = stubcheck.check(tmp_path).misses
    assert [(miss.line, miss.text) for miss in misses] == [(7, 'default" (1602).')]


def test_a_comment_deleted_from_the_stub_is_reported(tmp_path: Path) -> None:
    _tree(tmp_path, stub=STUB.replace("    /// clamped to \\[0.0, 1.0\\]\n", ""))
    misses = stubcheck.check(tmp_path).misses
    assert [(miss.line, miss.text) for miss in misses] == [(9, "clamped to [0.0, 1.0]")]


def test_a_comment_added_to_the_proto_alone_is_reported(tmp_path: Path) -> None:
    added = "  // Added and never regenerated.\n  uint32 max_edge = 1;"
    _tree(tmp_path, proto=PROTO.replace("  uint32 max_edge = 1;", added))
    misses = stubcheck.check(tmp_path).misses
    assert [(miss.line, miss.text) for miss in misses] == [(8, "Added and never regenerated.")]


def test_a_trailing_comment_is_compared_like_any_other(tmp_path: Path) -> None:
    """It is the kind a naive `//` split reads wrong, and a third of these comments are one."""
    _tree(tmp_path, proto=PROTO.replace("clamped to [0.0, 1.0]", "clamped to [0.0, 2.0]"))
    misses = stubcheck.check(tmp_path).misses
    assert [miss.text for miss in misses] == ["clamped to [0.0, 2.0]"]


def test_a_doc_comment_the_proto_never_wrote_is_not_this_gates_business(tmp_path: Path) -> None:
    """tonic documents its own client, so the reverse containment could never be a rule."""
    _tree(tmp_path)
    docs = protocomments.rust_docs(STUB)
    assert " Attempt to create a new client by connecting to a given endpoint." in docs
    assert stubcheck.check(tmp_path).misses == []


def test_the_file_header_is_not_compared(tmp_path: Path) -> None:
    """It attaches to no declaration, so the stub carries none of it and owes none of it."""
    header = "// Stubs are committed; regenerate with `just proto`.\n"
    _tree(tmp_path, proto=header + PROTO)
    assert stubcheck.check(tmp_path).misses == []


# ── the three re-spellings prost applies on the way in ─────────────────────────


def test_an_escaped_bracket_is_still_the_comment_the_proto_wrote(tmp_path: Path) -> None:
    _tree(tmp_path, proto=PROTO, stub=STUB)
    assert "\\[0.0, 1.0\\]" in STUB
    assert stubcheck.check(tmp_path).misses == []


def test_a_service_banner_survives_the_heading_marker_and_the_collapsed_rule(
    tmp_path: Path,
) -> None:
    _tree(tmp_path, proto=BANNER_PROTO, stub=BANNER_STUB)
    assert stubcheck.check(tmp_path).misses == []


def test_a_banner_whose_words_changed_is_still_reported(tmp_path: Path) -> None:
    """A normalization that swallowed the sentence with the markers would be a gate that cannot

    fail on a banner, and a banner is where the seam says which side hosts which service.
    """
    _tree(tmp_path, proto=BANNER_PROTO.replace("host-native", "dockerized"), stub=BANNER_STUB)
    misses = stubcheck.check(tmp_path).misses
    assert [miss.text for miss in misses] == [
        "BodyService is hosted by the body (dockerized). The brain is the client."
    ]


# ── failing closed ─────────────────────────────────────────────────────────────


def test_a_missing_proto_is_a_failure(tmp_path: Path) -> None:
    _tree(tmp_path)
    (tmp_path / stubcheck.PROTO).unlink()
    with pytest.raises(stubcheck.StubCheckError, match="cannot read proto/body"):
        stubcheck.check(tmp_path)


def test_a_missing_stub_is_a_failure(tmp_path: Path) -> None:
    _tree(tmp_path)
    (tmp_path / stubcheck.STUB).unlink()
    with pytest.raises(stubcheck.StubCheckError, match="cannot read body/crates"):
        stubcheck.check(tmp_path)


def test_a_stub_that_is_not_text_is_a_failure(tmp_path: Path) -> None:
    _tree(tmp_path)
    (tmp_path / stubcheck.STUB).write_bytes(b"\xff\xfe ///")
    with pytest.raises(stubcheck.StubCheckError, match="cannot read body/crates"):
        stubcheck.check(tmp_path)


def test_a_proto_with_no_syntax_line_is_a_failure(tmp_path: Path) -> None:
    _tree(tmp_path, proto=BODY)
    with pytest.raises(stubcheck.StubCheckError, match="no 'syntax = ' line"):
        stubcheck.check(tmp_path)


def test_a_proto_with_no_comment_at_all_is_a_failure_not_a_pass(tmp_path: Path) -> None:
    """A comparison over an empty collection would report success forever."""
    _tree(tmp_path, proto=HEAD)
    with pytest.raises(stubcheck.StubCheckError, match="no comment in proto/body"):
        stubcheck.check(tmp_path)


def test_a_stub_with_no_doc_comment_is_a_failure_not_a_pass(tmp_path: Path) -> None:
    """The other empty side, and the louder one: it is what a lost regeneration looks like."""
    _tree(tmp_path, stub="// This file is @generated by prost-build.\n")
    with pytest.raises(stubcheck.StubCheckError, match="no doc comment in body/crates"):
        stubcheck.check(tmp_path)


# ── what the comparison was over ───────────────────────────────────────────────


def test_check_counts_the_comments_and_the_doc_lines_it_read(tmp_path: Path) -> None:
    """Three numbers, none derivable from another: the stub always says more than the proto."""
    _tree(tmp_path)
    scanned = stubcheck.check(tmp_path)
    assert (scanned.leading, scanned.trailing, scanned.docs) == (3, 1, 5)


def test_main_states_what_it_read_beside_the_verdict(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _tree(tmp_path)
    assert stubcheck.main(["--root", str(tmp_path)]) == 0
    assert capsys.readouterr().out == (
        f"stubcheck OK: 4 proto comment(s) under {tmp_path} (3 leading, 1 trailing) appear in "
        f"the committed Rust stub, over 5 doc line(s) read\n"
    )


def test_main_reports_each_miss_and_exits_one(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _tree(tmp_path, proto=PROTO.replace("(1601)", "(1602)"))
    assert stubcheck.main(["--root", str(tmp_path)]) == 1
    captured = capsys.readouterr()
    assert "proto/body.proto:7:" in captured.out
    assert "1 proto comment(s) are missing" in captured.err
    assert "just proto" in captured.err


def test_main_rejects_a_root_that_is_not_a_directory(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert stubcheck.main(["--root", str(tmp_path / "nope")]) == 2
    assert "is not a directory" in capsys.readouterr().err


def test_main_reports_a_comparison_that_could_not_run(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert stubcheck.main(["--root", str(tmp_path)]) == 2
    assert "cannot read proto/body.proto" in capsys.readouterr().err


# ── the repo this gate guards ──────────────────────────────────────────────────


def test_the_repo_itself_is_clean() -> None:
    """The gate's own assertion, run as a test so `check-scripts` catches drift too."""
    assert stubcheck.check(REPO_ROOT).misses == []


def test_the_repo_really_carries_comments_for_this_gate_to_have_checked() -> None:
    """A guard on the guard: a proto read as empty would make the test above vacuously green."""
    scanned = stubcheck.check(REPO_ROOT)
    assert scanned.leading >= 150
    assert scanned.trailing >= 20
    assert scanned.docs >= 200


def test_the_real_stub_carries_every_re_spelling_this_gate_undoes() -> None:
    """Each normalization is dead code the day prost stops needing it, so each is pinned here.

    A normalization nothing exercises is the quieter half of a gate that cannot fail: it would
    keep passing on a tree where the shape it was written for no longer occurs, and the next
    person to change it would have nothing to change it against.
    """
    docs = protocomments.rust_docs((REPO_ROOT / stubcheck.STUB).read_text(encoding="utf-8"))
    assert any("\\[" in doc and "\\]" in doc for doc in docs)
    assert any(doc.strip().startswith("##") for doc in docs)
    assert any(doc.strip() == protocomments.RULE for doc in docs)


def test_main_passes_the_real_repo(capsys: pytest.CaptureFixture[str]) -> None:
    assert stubcheck.main(["--root", str(REPO_ROOT)]) == 0
    assert "stubcheck OK" in capsys.readouterr().out
