// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientEvent {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(oneof = "client_event::Event", tags = "2, 3, 4")]
    pub event: ::core::option::Option<client_event::Event>,
}
/// Nested message and enum types in `ClientEvent`.
pub mod client_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        /// text (+ optional attached capture) from the overlay
        #[prost(message, tag = "2")]
        UserTurn(super::UserTurn),
        /// stop generating the current turn
        #[prost(message, tag = "3")]
        Cancel(super::Cancel),
        /// the user's answer to a ConfirmRequest (ADR-0022)
        #[prost(message, tag = "4")]
        ConfirmResponse(super::ConfirmResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserTurn {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// e.g. a screen capture the user attached
    #[prost(message, repeated, tag = "2")]
    pub images: ::prost::alloc::vec::Vec<ImageBlob>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cancel {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerEvent {
    #[prost(oneof = "server_event::Event", tags = "1, 2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<server_event::Event>,
}
/// Nested message and enum types in `ServerEvent`.
pub mod server_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        /// streamed assistant tokens
        #[prost(message, tag = "1")]
        TextDelta(super::TextDelta),
        /// "reading email...", audit-visible tool use
        #[prost(message, tag = "2")]
        ToolActivity(super::ToolActivity),
        /// model swap in progress, queue position, etc.
        #[prost(message, tag = "3")]
        Status(super::StatusUpdate),
        #[prost(message, tag = "4")]
        TurnComplete(super::TurnComplete),
        #[prost(message, tag = "5")]
        Error(super::SeamError),
        /// a gated tool call awaits user approval (ADR-0022)
        #[prost(message, tag = "6")]
        ConfirmRequest(super::ConfirmRequest),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextDelta {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolActivity {
    #[prost(string, tag = "1")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub summary: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusUpdate {
    #[prost(string, tag = "1")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TurnComplete {
    #[prost(string, tag = "1")]
    pub turn_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeamError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Out-of-band user confirmation of a gated (outbound/irreversible) tool call (ADR-0022).
/// The brain emits ConfirmRequest mid-turn on the Converse stream and suspends the tool
/// call until the matching ConfirmResponse arrives, the timeout denies, or the stream
/// dies (deny). The human authorizes, never the model: an unanswered or unmatched
/// request always resolves as a denial (fail-closed, ADR-0013).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfirmRequest {
    /// correlation id, minted per request by the brain
    #[prost(string, tag = "1")]
    pub confirm_id: ::prost::alloc::string::String,
    /// what would run, e.g. "send_email"
    #[prost(string, tag = "2")]
    pub tool_name: ::prost::alloc::string::String,
    /// the exact draft being approved, one JSON object
    #[prost(string, tag = "3")]
    pub arguments_json: ::prost::alloc::string::String,
    /// why confirmation is required, shown verbatim
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfirmResponse {
    /// echoes the request it answers
    #[prost(string, tag = "1")]
    pub confirm_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub approved: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthReply {
    #[prost(bool, tag = "1")]
    pub ready: bool,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
/// Recent chats, most-recently-active first (ADR-0021). `limit` caps the count;
/// 0 means the server default.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSessionsRequest {
    #[prost(int32, tag = "1")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsReply {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<SessionSummary>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionSummary {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// derived: first user message, one line, truncated
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    /// derived: last message text, one line, truncated
    #[prost(string, tag = "3")]
    pub preview: ::prost::alloc::string::String,
    /// for a relative timestamp in the switcher
    #[prost(int64, tag = "4")]
    pub last_activity_unix_ms: i64,
}
/// One session's persisted history, in append order (ADR-0021).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSessionMessagesRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionMessagesReply {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<SessionMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionMessage {
    /// "user" | "assistant" are the only persisted roles
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub turn_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub at_unix_ms: i64,
}
/// Reminder pull-delivery views (ADR-0025). All sessions are listed deliberately because
/// a single-user assistant has one user to remind; session_id rides along so the
/// overlay can later offer "open the conversation this came from" without a wire change.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDueRemindersRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDueRemindersReply {
    #[prost(message, repeated, tag = "1")]
    pub reminders: ::prost::alloc::vec::Vec<DueReminder>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DueReminder {
    #[prost(string, tag = "1")]
    pub reminder_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    /// when it became deliverable
    #[prost(int64, tag = "3")]
    pub fired_at_unix_ms: i64,
    #[prost(bool, tag = "4")]
    pub recurring: bool,
    /// untrusted provenance, so the overlay may badge it
    #[prost(bool, tag = "5")]
    pub tainted: bool,
    /// origin chat ("" until session attribution lands)
    #[prost(string, tag = "6")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckReminderRequest {
    #[prost(string, tag = "1")]
    pub reminder_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckReminderReply {
    #[prost(bool, tag = "1")]
    pub acked: bool,
}
/// Empty = primary display; later: display index / window handle.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptureScreenRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptureScreenReply {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<ImageBlob>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageBlob {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// e.g. image/png
    #[prost(string, tag = "2")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub width: u32,
    #[prost(uint32, tag = "4")]
    pub height: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVolumeRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetVolumeRequest {
    /// Both fields have explicit presence so callers can set level, mute, or both.
    ///
    /// clamped to \[0.0, 1.0\]
    #[prost(float, optional, tag = "1")]
    pub level: ::core::option::Option<f32>,
    #[prost(bool, optional, tag = "2")]
    pub mute: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VolumeState {
    #[prost(float, tag = "1")]
    pub level: f32,
    #[prost(bool, tag = "2")]
    pub muted: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InjectInputRequest {
    #[prost(oneof = "inject_input_request::Input", tags = "1, 2")]
    pub input: ::core::option::Option<inject_input_request::Input>,
}
/// Nested message and enum types in `InjectInputRequest`.
pub mod inject_input_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Input {
        /// literal text entry
        #[prost(message, tag = "1")]
        TypeText(super::TypeText),
        /// e.g. ctrl+shift+esc
        #[prost(message, tag = "2")]
        KeyChord(super::KeyChord),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypeText {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyChord {
    #[prost(string, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InjectInputReply {
    #[prost(bool, tag = "1")]
    pub applied: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub reminder_id: ::prost::alloc::string::String,
    /// symmetric with DueReminder, so the toast may badge provenance
    #[prost(bool, tag = "4")]
    pub tainted: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyReply {
    #[prost(bool, tag = "1")]
    pub shown: bool,
}
/// Generated client implementations.
pub mod brain_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ---
    ///
    /// ## BrainService is hosted by the brain (Docker). The body is the client.
    #[derive(Debug, Clone)]
    pub struct BrainServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BrainServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BrainServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BrainServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BrainServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// One conversational exchange stream per overlay session. Client events carry user
        /// turns and cancellations; server events stream tokens, tool activity, and status
        /// (e.g. "brain model loading" during a handoff, so the overlay can show progress).
        pub async fn converse(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ClientEvent>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServerEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/Converse",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "Converse"));
            self.inner.streaming(req, path, codec).await
        }
        /// Liveness/readiness for the overlay to display connection state.
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "Health"));
            self.inner.unary(req, path, codec).await
        }
        /// Read-only views of the durable session store (ADR-0021): the overlay's chat
        /// list + switcher + cycling. Snapshots, not streams; they add no write path and
        /// so cannot touch the one hard rule beyond reading what the store already holds.
        pub async fn list_sessions(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSessionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSessionsReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/ListSessions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "ListSessions"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_session_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSessionMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionMessagesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/GetSessionMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cortex.seam.v1.BrainService", "GetSessionMessages"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Reminder pull-delivery (ADR-0025): the overlay surfaces fired-but-undelivered
        /// reminders when it opens and acks what it showed. ListDueReminders is a read-only
        /// store view (the ADR-0021 pattern); AckReminder is the one narrow idempotent write
        /// the pull loop needs (acking a non-deliverable id is a no-op acked=false). With no
        /// ScheduleStore wired both answer benignly (empty / acked=false), never an error, because
        /// a schedule-free brain is indistinguishable from one with nothing due.
        pub async fn list_due_reminders(
            &mut self,
            request: impl tonic::IntoRequest<super::ListDueRemindersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDueRemindersReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/ListDueReminders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cortex.seam.v1.BrainService", "ListDueReminders"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn ack_reminder(
            &mut self,
            request: impl tonic::IntoRequest<super::AckReminderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckReminderReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/AckReminder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "AckReminder"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod brain_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BrainServiceServer.
    #[async_trait]
    pub trait BrainService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Converse method.
        type ConverseStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ServerEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// One conversational exchange stream per overlay session. Client events carry user
        /// turns and cancellations; server events stream tokens, tool activity, and status
        /// (e.g. "brain model loading" during a handoff, so the overlay can show progress).
        async fn converse(
            &self,
            request: tonic::Request<tonic::Streaming<super::ClientEvent>>,
        ) -> std::result::Result<tonic::Response<Self::ConverseStream>, tonic::Status>;
        /// Liveness/readiness for the overlay to display connection state.
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthReply>, tonic::Status>;
        /// Read-only views of the durable session store (ADR-0021): the overlay's chat
        /// list + switcher + cycling. Snapshots, not streams; they add no write path and
        /// so cannot touch the one hard rule beyond reading what the store already holds.
        async fn list_sessions(
            &self,
            request: tonic::Request<super::ListSessionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSessionsReply>,
            tonic::Status,
        >;
        async fn get_session_messages(
            &self,
            request: tonic::Request<super::GetSessionMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionMessagesReply>,
            tonic::Status,
        >;
        /// Reminder pull-delivery (ADR-0025): the overlay surfaces fired-but-undelivered
        /// reminders when it opens and acks what it showed. ListDueReminders is a read-only
        /// store view (the ADR-0021 pattern); AckReminder is the one narrow idempotent write
        /// the pull loop needs (acking a non-deliverable id is a no-op acked=false). With no
        /// ScheduleStore wired both answer benignly (empty / acked=false), never an error, because
        /// a schedule-free brain is indistinguishable from one with nothing due.
        async fn list_due_reminders(
            &self,
            request: tonic::Request<super::ListDueRemindersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDueRemindersReply>,
            tonic::Status,
        >;
        async fn ack_reminder(
            &self,
            request: tonic::Request<super::AckReminderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckReminderReply>,
            tonic::Status,
        >;
    }
    /// ---
    ///
    /// ## BrainService is hosted by the brain (Docker). The body is the client.
    #[derive(Debug)]
    pub struct BrainServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BrainServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BrainServiceServer<T>
    where
        T: BrainService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cortex.seam.v1.BrainService/Converse" => {
                    #[allow(non_camel_case_types)]
                    struct ConverseSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::StreamingService<super::ClientEvent>
                    for ConverseSvc<T> {
                        type Response = super::ServerEvent;
                        type ResponseStream = T::ConverseStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::ClientEvent>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::converse(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConverseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/ListSessions" => {
                    #[allow(non_camel_case_types)]
                    struct ListSessionsSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::ListSessionsRequest>
                    for ListSessionsSvc<T> {
                        type Response = super::ListSessionsReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListSessionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::list_sessions(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSessionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/GetSessionMessages" => {
                    #[allow(non_camel_case_types)]
                    struct GetSessionMessagesSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::GetSessionMessagesRequest>
                    for GetSessionMessagesSvc<T> {
                        type Response = super::GetSessionMessagesReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSessionMessagesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::get_session_messages(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSessionMessagesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/ListDueReminders" => {
                    #[allow(non_camel_case_types)]
                    struct ListDueRemindersSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::ListDueRemindersRequest>
                    for ListDueRemindersSvc<T> {
                        type Response = super::ListDueRemindersReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListDueRemindersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::list_due_reminders(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListDueRemindersSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/AckReminder" => {
                    #[allow(non_camel_case_types)]
                    struct AckReminderSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::AckReminderRequest>
                    for AckReminderSvc<T> {
                        type Response = super::AckReminderReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AckReminderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::ack_reminder(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AckReminderSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BrainServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cortex.seam.v1.BrainService";
    impl<T> tonic::server::NamedService for BrainServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated client implementations.
pub mod body_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ---
    ///
    /// ## BodyService is hosted by the body (host-native). The brain is the client.
    /// Exposes host OS capabilities behind the body's Rust traits.
    /// (Whether these also surface to models as MCP tools: ADR-0001 open question #2.
    /// Connectivity direction: ADR-0001 open question #3.)
    #[derive(Debug, Clone)]
    pub struct BodyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BodyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BodyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BodyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BodyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn capture_screen(
            &mut self,
            request: impl tonic::IntoRequest<super::CaptureScreenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptureScreenReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/CaptureScreen",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "CaptureScreen"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::GetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/GetVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "GetVolume"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::SetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/SetVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "SetVolume"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn inject_input(
            &mut self,
            request: impl tonic::IntoRequest<super::InjectInputRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InjectInputReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/InjectInput",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "InjectInput"));
            self.inner.unary(req, path, codec).await
        }
        /// Show a native notification (ADR-0025): the brain->body push half of reminder
        /// delivery. shown=true means the OS accepted/displayed the toast. The ticker then
        /// acks the reminder (a toast IS delivery); false or an error leaves it deliverable
        /// for the pull path. The body renders title/body as inert escaped text: reminder
        /// text can be attacker-influenced (tainted marks it), and a toast template is XML.
        pub async fn notify(
            &mut self,
            request: impl tonic::IntoRequest<super::NotifyRequest>,
        ) -> std::result::Result<tonic::Response<super::NotifyReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/Notify",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "Notify"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod body_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BodyServiceServer.
    #[async_trait]
    pub trait BodyService: std::marker::Send + std::marker::Sync + 'static {
        async fn capture_screen(
            &self,
            request: tonic::Request<super::CaptureScreenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptureScreenReply>,
            tonic::Status,
        >;
        async fn get_volume(
            &self,
            request: tonic::Request<super::GetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status>;
        async fn set_volume(
            &self,
            request: tonic::Request<super::SetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status>;
        async fn inject_input(
            &self,
            request: tonic::Request<super::InjectInputRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InjectInputReply>,
            tonic::Status,
        >;
        /// Show a native notification (ADR-0025): the brain->body push half of reminder
        /// delivery. shown=true means the OS accepted/displayed the toast. The ticker then
        /// acks the reminder (a toast IS delivery); false or an error leaves it deliverable
        /// for the pull path. The body renders title/body as inert escaped text: reminder
        /// text can be attacker-influenced (tainted marks it), and a toast template is XML.
        async fn notify(
            &self,
            request: tonic::Request<super::NotifyRequest>,
        ) -> std::result::Result<tonic::Response<super::NotifyReply>, tonic::Status>;
    }
    /// ---
    ///
    /// ## BodyService is hosted by the body (host-native). The brain is the client.
    /// Exposes host OS capabilities behind the body's Rust traits.
    /// (Whether these also surface to models as MCP tools: ADR-0001 open question #2.
    /// Connectivity direction: ADR-0001 open question #3.)
    #[derive(Debug)]
    pub struct BodyServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BodyServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BodyServiceServer<T>
    where
        T: BodyService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cortex.seam.v1.BodyService/CaptureScreen" => {
                    #[allow(non_camel_case_types)]
                    struct CaptureScreenSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::CaptureScreenRequest>
                    for CaptureScreenSvc<T> {
                        type Response = super::CaptureScreenReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CaptureScreenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::capture_screen(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CaptureScreenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/GetVolume" => {
                    #[allow(non_camel_case_types)]
                    struct GetVolumeSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::GetVolumeRequest>
                    for GetVolumeSvc<T> {
                        type Response = super::VolumeState;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetVolumeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::get_volume(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetVolumeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/SetVolume" => {
                    #[allow(non_camel_case_types)]
                    struct SetVolumeSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::SetVolumeRequest>
                    for SetVolumeSvc<T> {
                        type Response = super::VolumeState;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetVolumeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::set_volume(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetVolumeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/InjectInput" => {
                    #[allow(non_camel_case_types)]
                    struct InjectInputSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::InjectInputRequest>
                    for InjectInputSvc<T> {
                        type Response = super::InjectInputReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InjectInputRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::inject_input(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InjectInputSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/Notify" => {
                    #[allow(non_camel_case_types)]
                    struct NotifySvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::NotifyRequest>
                    for NotifySvc<T> {
                        type Response = super::NotifyReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::NotifyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::notify(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = NotifySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BodyServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cortex.seam.v1.BodyService";
    impl<T> tonic::server::NamedService for BodyServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
