// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientEvent {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(oneof = "client_event::Event", tags = "2, 3, 4")]
    pub event: ::core::option::Option<client_event::Event>,
}
/// Nested message and enum types in `ClientEvent`.
pub mod client_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        /// text, and the images the user attached, if any
        #[prost(message, tag = "2")]
        UserTurn(super::UserTurn),
        /// stop generating the current turn
        #[prost(message, tag = "3")]
        Cancel(super::Cancel),
        /// the user's answer to a ConfirmRequest
        #[prost(message, tag = "4")]
        ConfirmResponse(super::ConfirmResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserTurn {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// Images the user attached, for this turn only: at most 4, each PNG, JPEG or WebP of at most
    /// 6 MiB with width and height set. Any other ends the stream with code attachment_refused.
    #[prost(message, repeated, tag = "2")]
    pub images: ::prost::alloc::vec::Vec<ImageBlob>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Cancel {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerEvent {
    #[prost(oneof = "server_event::Event", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub event: ::core::option::Option<server_event::Event>,
}
/// Nested message and enum types in `ServerEvent`.
pub mod server_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        /// streamed assistant tokens
        #[prost(message, tag = "1")]
        TextDelta(super::TextDelta),
        /// a tool is about to run
        #[prost(message, tag = "2")]
        ToolActivity(super::ToolActivity),
        /// a model swap in progress, a queue position
        #[prost(message, tag = "3")]
        Status(super::StatusUpdate),
        #[prost(message, tag = "4")]
        TurnComplete(super::TurnComplete),
        #[prost(message, tag = "5")]
        Error(super::SeamError),
        /// a tool call is waiting for the user's approval
        #[prost(message, tag = "6")]
        ConfirmRequest(super::ConfirmRequest),
        /// the brain stopped waiting for an answer
        #[prost(message, tag = "7")]
        ConfirmResolved(super::ConfirmResolved),
        /// how a tool call announced above ended
        #[prost(message, tag = "8")]
        ToolOutcome(super::ToolOutcome),
        /// the turn is still running, and what it waits on
        #[prost(message, tag = "9")]
        Heartbeat(super::Heartbeat),
    }
}
/// Sent by the stream itself, not by the turn, once per heartbeat period while a turn task is
/// running and nothing else is waiting to be sent, so a live brain and a dead one differ within
/// minutes. It repeats the turn's current wait, which a dropped StatusUpdate may have lost.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Heartbeat {
    /// a StatusUpdate state such as queued or calling, or "" for none
    #[prost(string, tag = "1")]
    pub wait: ::prost::alloc::string::String,
    /// the sentence the overlay shows for the wait
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextDelta {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolActivity {
    #[prost(string, tag = "1")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub summary: ::prost::alloc::string::String,
}
/// How one announced tool call ended. A subagent's steps also reach this stream as activities,
/// over a channel that drops events when full, so an activity with no outcome is ordinary and
/// the proto3 default false is the safe reading: it leaves a surface at its weaker claim.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolOutcome {
    #[prost(string, tag = "1")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusUpdate {
    #[prost(string, tag = "1")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TurnComplete {
    #[prost(string, tag = "1")]
    pub turn_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeamError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// The user's approval of an outbound or irreversible tool call. The brain emits ConfirmRequest
/// mid-turn and suspends the call until the matching ConfirmResponse arrives, the timeout denies
/// it, or the stream dies. An unanswered or unmatched request always ends as a denial.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfirmRequest {
    /// correlation id, minted per request by the brain
    #[prost(string, tag = "1")]
    pub confirm_id: ::prost::alloc::string::String,
    /// what would run, for example "send_email"
    #[prost(string, tag = "2")]
    pub tool_name: ::prost::alloc::string::String,
    /// the exact draft being approved, one JSON object
    #[prost(string, tag = "3")]
    pub arguments_json: ::prost::alloc::string::String,
    /// why confirmation is required, shown to the user as written
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfirmResponse {
    /// echoes the request it answers
    #[prost(string, tag = "1")]
    pub confirm_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub approved: bool,
}
/// A ConfirmRequest the brain stopped waiting on, so the overlay can close a card the user can no
/// longer answer. Emitted only for endings the client cannot already know: the confirm timeout,
/// and client input half-closing.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfirmResolved {
    /// which ConfirmRequest ended
    #[prost(string, tag = "1")]
    pub confirm_id: ::prost::alloc::string::String,
    /// "timeout" or "unavailable"; it explains, it never approves
    #[prost(string, tag = "2")]
    pub outcome: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {}
/// `detail` is one line for a client that shows one: the reason when the brain is not ready, and
/// otherwise its serving notes joined, or its version. `notes` has the same serving notes one fact
/// per entry, in the same order, so a client can show a line per fact. It is empty when not ready.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthReply {
    #[prost(bool, tag = "1")]
    pub ready: bool,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub notes: ::prost::alloc::vec::Vec<HealthNote>,
}
/// One fact about a brain that is serving, as a sentence for a person to read.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthNote {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
/// Recent chats, most-recently-active first. `limit` caps the count; 0 means the server default.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSessionsRequest {
    #[prost(int32, tag = "1")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsReply {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<SessionSummary>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionSummary {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// derived: first user message, one line, truncated
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    /// derived: last message text, one line, truncated
    #[prost(string, tag = "3")]
    pub preview: ::prost::alloc::string::String,
    /// for a relative timestamp in the switcher
    #[prost(int64, tag = "4")]
    pub last_activity_unix_ms: i64,
    /// listed whatever its age, above the chats sorted by recency
    #[prost(bool, tag = "5")]
    pub hoisted: bool,
}
/// One session's stored history, in append order.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSessionMessagesRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionMessagesReply {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<SessionMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionMessage {
    /// "user" or "assistant", the only stored roles
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub turn_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub at_unix_ms: i64,
}
/// Renames one chat. `title` is the new display label, and "" clears any custom or
/// brain-generated title. The reply is a bare acknowledgement; a store failure arrives as an
/// UNAVAILABLE status.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameSessionRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameSessionReply {}
/// Deletes one chat, its transcript and its private memories. The reply is a bare
/// acknowledgement; a store or memory failure arrives as UNAVAILABLE and the call is idempotent,
/// so a later attempt finishes it. A memory reply the brain cannot decode arrives as INTERNAL.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSessionRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSessionReply {}
/// Hoists or lowers one chat. The reply is a bare acknowledgement; a store failure arrives as an
/// UNAVAILABLE status. Setting the same value twice changes nothing.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetSessionHoistedRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub hoisted: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetSessionHoistedReply {}
/// The user's settings record. One pair is one setting; the brain stores and returns them as
/// given and never reads a value, so adding a setting costs no change here.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Preference {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPreferencesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPreferencesReply {
    #[prost(message, repeated, tag = "1")]
    pub preferences: ::prost::alloc::vec::Vec<Preference>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetPreferenceRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetPreferenceReply {}
/// Reminders that have fired and are still undelivered, across every session, because a
/// single-user assistant has one user to remind. session_id is sent too, so the overlay can later
/// offer to open the conversation a reminder came from without a change here.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDueRemindersRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDueRemindersReply {
    #[prost(message, repeated, tag = "1")]
    pub reminders: ::prost::alloc::vec::Vec<DueReminder>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DueReminder {
    #[prost(string, tag = "1")]
    pub reminder_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    /// when it became deliverable
    #[prost(int64, tag = "3")]
    pub fired_at_unix_ms: i64,
    #[prost(bool, tag = "4")]
    pub recurring: bool,
    /// untrusted origin, so the overlay may mark it
    #[prost(bool, tag = "5")]
    pub tainted: bool,
    /// the chat it came from; "" when there was none
    #[prost(string, tag = "6")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckReminderRequest {
    #[prost(string, tag = "1")]
    pub reminder_id: ::prost::alloc::string::String,
    /// Which fire this ack delivers, from the card's DueReminder.fired_at_unix_ms. The brain
    /// clears the slot only while it still holds that fire, so a card dismissed after a later fire
    /// replaced it clears nothing. 0, from a body built before this field, acks whichever is held.
    #[prost(int64, tag = "2")]
    pub fired_at_unix_ms: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckReminderReply {
    #[prost(bool, tag = "1")]
    pub acked: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptureScreenRequest {
    /// Longest edge of the returned image, in physical pixels. 0 means "the body's
    /// default" (1600). The body clamps it and, being proto3, may ignore it, so the brain checks
    /// the reply rather than relying on it.
    #[prost(uint32, tag = "1")]
    pub max_edge: u32,
    /// What to point at. A body older than this field ignores it, so the brain checks the reply.
    /// An unrecognized value reads as CAPTURE_TARGET_DISPLAY.
    #[prost(enumeration = "CaptureTarget", tag = "2")]
    pub target: i32,
    /// The most bytes the caller will accept, so the brain's image budget and the body's limit are
    /// one number. 0 means the body's own limit, and anything larger is clamped down to it, so this
    /// can only tighten the bound. Like max_edge, the brain checks the reply.
    #[prost(uint32, tag = "3")]
    pub max_bytes: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CaptureScreenReply {
    #[prost(message, optional, tag = "1")]
    pub image: ::core::option::Option<ImageBlob>,
    /// What the body pointed at, so the brain does not describe a crop as a shrunk screen. It is
    /// read off the encoded picture rather than off the request, so a window filling the display
    /// answers CAPTURE_TARGET_DISPLAY, and the zero is DISPLAY.
    #[prost(enumeration = "CaptureTarget", tag = "2")]
    pub resolved_target: i32,
    /// The size of the part of the display the picture shows, before the downscale: the window's
    /// on-screen part for FOCUS, the display for DISPLAY. A picture smaller than this was resampled,
    /// which a window's picture cannot show on its own. 0 is a body older than these fields.
    #[prost(uint32, tag = "3")]
    pub target_width: u32,
    #[prost(uint32, tag = "4")]
    pub target_height: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageBlob {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// for example image/png
    #[prost(string, tag = "2")]
    pub mime_type: ::prost::alloc::string::String,
    /// physical pixels, after the body's downscale
    #[prost(uint32, tag = "3")]
    pub width: u32,
    #[prost(uint32, tag = "4")]
    pub height: u32,
    /// The display's own size before the downscale, so the model can say the text is too small to
    /// read instead of guessing.
    #[prost(uint32, tag = "5")]
    pub source_width: u32,
    #[prost(uint32, tag = "6")]
    pub source_height: u32,
    /// When the pixels were read, so a multi-round turn can tell how old they are.
    #[prost(int64, tag = "7")]
    pub captured_at_unix_ms: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVolumeRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetVolumeRequest {
    /// Both fields have explicit presence, so a caller can set level, mute, or both.
    ///
    /// clamped to \[0.0, 1.0\]
    #[prost(float, optional, tag = "1")]
    pub level: ::core::option::Option<f32>,
    #[prost(bool, optional, tag = "2")]
    pub mute: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VolumeState {
    #[prost(float, tag = "1")]
    pub level: f32,
    #[prost(bool, tag = "2")]
    pub muted: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InjectInputRequest {
    #[prost(oneof = "inject_input_request::Input", tags = "1, 2")]
    pub input: ::core::option::Option<inject_input_request::Input>,
}
/// Nested message and enum types in `InjectInputRequest`.
pub mod inject_input_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Input {
        /// literal text entry
        #[prost(message, tag = "1")]
        TypeText(super::TypeText),
        /// for example ctrl+shift+esc
        #[prost(message, tag = "2")]
        KeyChord(super::KeyChord),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypeText {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeyChord {
    #[prost(string, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InjectInputReply {
    #[prost(bool, tag = "1")]
    pub applied: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub reminder_id: ::prost::alloc::string::String,
    /// matches DueReminder, so the toast can mark where the text came from
    #[prost(bool, tag = "4")]
    pub tainted: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyReply {
    #[prost(bool, tag = "1")]
    pub shown: bool,
}
/// What the body points the camera at. A closed set the body resolves, never a rectangle the
/// caller names: only the body knows where windows are, and a caller that guessed one would spend
/// a whole capture on the wrong part of the screen.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CaptureTarget {
    /// The primary display, whole, and the proto3 default.
    Display = 0,
    /// The topmost visible top-level window that is neither the body's own nor excluded from
    /// capture. Not the foreground window: the overlay is in front when this runs. With no such
    /// window the body answers FAILED_PRECONDITION, because a fallback would capture more.
    Focus = 1,
}
impl CaptureTarget {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Display => "CAPTURE_TARGET_DISPLAY",
            Self::Focus => "CAPTURE_TARGET_FOCUS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CAPTURE_TARGET_DISPLAY" => Some(Self::Display),
            "CAPTURE_TARGET_FOCUS" => Some(Self::Focus),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod brain_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ---
    ///
    /// ## BrainService is hosted by the brain, in Docker. The body is the client.
    #[derive(Debug, Clone)]
    pub struct BrainServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BrainServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BrainServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BrainServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BrainServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// One conversational exchange per overlay session. Client events send user turns and
        /// cancellations; server events stream tokens, tool activity and status, such as a model
        /// loading during a handoff.
        pub async fn converse(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::ClientEvent>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ServerEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/Converse",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "Converse"));
            self.inner.streaming(req, path, codec).await
        }
        /// Liveness and readiness, for the overlay's connection indicator.
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "Health"));
            self.inner.unary(req, path, codec).await
        }
        /// Read-only views of the session store, for the overlay's chat list and switcher.
        pub async fn list_sessions(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSessionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSessionsReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/ListSessions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "ListSessions"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_session_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSessionMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionMessagesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/GetSessionMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cortex.seam.v1.BrainService", "GetSessionMessages"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Reminder pull delivery: the overlay shows what has fired and is still undelivered, then
        /// acks what it showed. A brain with no schedule store answers an empty list and acked=false
        /// rather than an error, because it cannot be told from one with nothing due.
        pub async fn list_due_reminders(
            &mut self,
            request: impl tonic::IntoRequest<super::ListDueRemindersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDueRemindersReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/ListDueReminders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cortex.seam.v1.BrainService", "ListDueReminders"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn ack_reminder(
            &mut self,
            request: impl tonic::IntoRequest<super::AckReminderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckReminderReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/AckReminder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "AckReminder"));
            self.inner.unary(req, path, codec).await
        }
        /// Renames a chat. Reachable only from the overlay's own list controls, never from a model or
        /// a tool, and it stores a display title only, never conversation content. An empty title
        /// clears the override, so the title derived from the first message applies again.
        pub async fn rename_session(
            &mut self,
            request: impl tonic::IntoRequest<super::RenameSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RenameSessionReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/RenameSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "RenameSession"));
            self.inner.unary(req, path, codec).await
        }
        /// Deletes a chat: destructive and irreversible. The transcript, the catalog entry and the
        /// session's private memories all go. The overlay asks the user to confirm before sending
        /// this, and the body makes exactly one attempt so a lost reply cannot destroy twice.
        pub async fn delete_session(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteSessionReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/DeleteSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "DeleteSession"));
            self.inner.unary(req, path, codec).await
        }
        /// Hoists or lowers a chat. A hoisted chat is listed whatever its age, above the chats
        /// listed by recency. Reachable only from the overlay's list controls, and the body
        /// makes exactly one attempt.
        pub async fn set_session_hoisted(
            &mut self,
            request: impl tonic::IntoRequest<super::SetSessionHoistedRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetSessionHoistedReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/SetSessionHoisted",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cortex.seam.v1.BrainService", "SetSessionHoisted"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// The user's settings: a durable key/value record the brain owns, so a choice survives a body
        /// restart. Keys are namespaced names the caller owns ("overlay.theme"); values are short
        /// strings the brain stores and returns without reading them. An empty value clears the key.
        pub async fn get_preferences(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPreferencesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPreferencesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/GetPreferences",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cortex.seam.v1.BrainService", "GetPreferences"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_preference(
            &mut self,
            request: impl tonic::IntoRequest<super::SetPreferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPreferenceReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BrainService/SetPreference",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BrainService", "SetPreference"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod brain_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BrainServiceServer.
    #[async_trait]
    pub trait BrainService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Converse method.
        type ConverseStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ServerEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// One conversational exchange per overlay session. Client events send user turns and
        /// cancellations; server events stream tokens, tool activity and status, such as a model
        /// loading during a handoff.
        async fn converse(
            &self,
            request: tonic::Request<tonic::Streaming<super::ClientEvent>>,
        ) -> std::result::Result<tonic::Response<Self::ConverseStream>, tonic::Status>;
        /// Liveness and readiness, for the overlay's connection indicator.
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthReply>, tonic::Status>;
        /// Read-only views of the session store, for the overlay's chat list and switcher.
        async fn list_sessions(
            &self,
            request: tonic::Request<super::ListSessionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListSessionsReply>,
            tonic::Status,
        >;
        async fn get_session_messages(
            &self,
            request: tonic::Request<super::GetSessionMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionMessagesReply>,
            tonic::Status,
        >;
        /// Reminder pull delivery: the overlay shows what has fired and is still undelivered, then
        /// acks what it showed. A brain with no schedule store answers an empty list and acked=false
        /// rather than an error, because it cannot be told from one with nothing due.
        async fn list_due_reminders(
            &self,
            request: tonic::Request<super::ListDueRemindersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListDueRemindersReply>,
            tonic::Status,
        >;
        async fn ack_reminder(
            &self,
            request: tonic::Request<super::AckReminderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AckReminderReply>,
            tonic::Status,
        >;
        /// Renames a chat. Reachable only from the overlay's own list controls, never from a model or
        /// a tool, and it stores a display title only, never conversation content. An empty title
        /// clears the override, so the title derived from the first message applies again.
        async fn rename_session(
            &self,
            request: tonic::Request<super::RenameSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RenameSessionReply>,
            tonic::Status,
        >;
        /// Deletes a chat: destructive and irreversible. The transcript, the catalog entry and the
        /// session's private memories all go. The overlay asks the user to confirm before sending
        /// this, and the body makes exactly one attempt so a lost reply cannot destroy twice.
        async fn delete_session(
            &self,
            request: tonic::Request<super::DeleteSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteSessionReply>,
            tonic::Status,
        >;
        /// Hoists or lowers a chat. A hoisted chat is listed whatever its age, above the chats
        /// listed by recency. Reachable only from the overlay's list controls, and the body
        /// makes exactly one attempt.
        async fn set_session_hoisted(
            &self,
            request: tonic::Request<super::SetSessionHoistedRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetSessionHoistedReply>,
            tonic::Status,
        >;
        /// The user's settings: a durable key/value record the brain owns, so a choice survives a body
        /// restart. Keys are namespaced names the caller owns ("overlay.theme"); values are short
        /// strings the brain stores and returns without reading them. An empty value clears the key.
        async fn get_preferences(
            &self,
            request: tonic::Request<super::GetPreferencesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPreferencesReply>,
            tonic::Status,
        >;
        async fn set_preference(
            &self,
            request: tonic::Request<super::SetPreferenceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPreferenceReply>,
            tonic::Status,
        >;
    }
    /// ---
    ///
    /// ## BrainService is hosted by the brain, in Docker. The body is the client.
    #[derive(Debug)]
    pub struct BrainServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BrainServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BrainServiceServer<T>
    where
        T: BrainService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cortex.seam.v1.BrainService/Converse" => {
                    #[allow(non_camel_case_types)]
                    struct ConverseSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::StreamingService<super::ClientEvent>
                    for ConverseSvc<T> {
                        type Response = super::ServerEvent;
                        type ResponseStream = T::ConverseStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::ClientEvent>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::converse(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConverseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/ListSessions" => {
                    #[allow(non_camel_case_types)]
                    struct ListSessionsSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::ListSessionsRequest>
                    for ListSessionsSvc<T> {
                        type Response = super::ListSessionsReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListSessionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::list_sessions(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSessionsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/GetSessionMessages" => {
                    #[allow(non_camel_case_types)]
                    struct GetSessionMessagesSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::GetSessionMessagesRequest>
                    for GetSessionMessagesSvc<T> {
                        type Response = super::GetSessionMessagesReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSessionMessagesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::get_session_messages(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSessionMessagesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/ListDueReminders" => {
                    #[allow(non_camel_case_types)]
                    struct ListDueRemindersSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::ListDueRemindersRequest>
                    for ListDueRemindersSvc<T> {
                        type Response = super::ListDueRemindersReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListDueRemindersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::list_due_reminders(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListDueRemindersSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/AckReminder" => {
                    #[allow(non_camel_case_types)]
                    struct AckReminderSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::AckReminderRequest>
                    for AckReminderSvc<T> {
                        type Response = super::AckReminderReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AckReminderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::ack_reminder(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AckReminderSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/RenameSession" => {
                    #[allow(non_camel_case_types)]
                    struct RenameSessionSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::RenameSessionRequest>
                    for RenameSessionSvc<T> {
                        type Response = super::RenameSessionReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RenameSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::rename_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RenameSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/DeleteSession" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteSessionSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::DeleteSessionRequest>
                    for DeleteSessionSvc<T> {
                        type Response = super::DeleteSessionReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::delete_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteSessionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/SetSessionHoisted" => {
                    #[allow(non_camel_case_types)]
                    struct SetSessionHoistedSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::SetSessionHoistedRequest>
                    for SetSessionHoistedSvc<T> {
                        type Response = super::SetSessionHoistedReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetSessionHoistedRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::set_session_hoisted(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetSessionHoistedSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/GetPreferences" => {
                    #[allow(non_camel_case_types)]
                    struct GetPreferencesSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::GetPreferencesRequest>
                    for GetPreferencesSvc<T> {
                        type Response = super::GetPreferencesReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPreferencesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::get_preferences(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPreferencesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BrainService/SetPreference" => {
                    #[allow(non_camel_case_types)]
                    struct SetPreferenceSvc<T: BrainService>(pub Arc<T>);
                    impl<
                        T: BrainService,
                    > tonic::server::UnaryService<super::SetPreferenceRequest>
                    for SetPreferenceSvc<T> {
                        type Response = super::SetPreferenceReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetPreferenceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrainService>::set_preference(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetPreferenceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BrainServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cortex.seam.v1.BrainService";
    impl<T> tonic::server::NamedService for BrainServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated client implementations.
pub mod body_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ---
    ///
    /// ## BodyService is hosted by the body. The brain is the client.
    #[derive(Debug, Clone)]
    pub struct BodyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BodyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BodyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BodyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BodyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn capture_screen(
            &mut self,
            request: impl tonic::IntoRequest<super::CaptureScreenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptureScreenReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/CaptureScreen",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "CaptureScreen"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::GetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/GetVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "GetVolume"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::SetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/SetVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "SetVolume"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn inject_input(
            &mut self,
            request: impl tonic::IntoRequest<super::InjectInputRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InjectInputReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/InjectInput",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "InjectInput"));
            self.inner.unary(req, path, codec).await
        }
        /// Shows a native notification, which is the push half of reminder delivery. shown=true means
        /// the OS displayed it, and the brain then acks the reminder; false or an error leaves the
        /// reminder deliverable. The body escapes the text, because a toast template is XML.
        pub async fn notify(
            &mut self,
            request: impl tonic::IntoRequest<super::NotifyRequest>,
        ) -> std::result::Result<tonic::Response<super::NotifyReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cortex.seam.v1.BodyService/Notify",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cortex.seam.v1.BodyService", "Notify"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod body_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BodyServiceServer.
    #[async_trait]
    pub trait BodyService: std::marker::Send + std::marker::Sync + 'static {
        async fn capture_screen(
            &self,
            request: tonic::Request<super::CaptureScreenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptureScreenReply>,
            tonic::Status,
        >;
        async fn get_volume(
            &self,
            request: tonic::Request<super::GetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status>;
        async fn set_volume(
            &self,
            request: tonic::Request<super::SetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::VolumeState>, tonic::Status>;
        async fn inject_input(
            &self,
            request: tonic::Request<super::InjectInputRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InjectInputReply>,
            tonic::Status,
        >;
        /// Shows a native notification, which is the push half of reminder delivery. shown=true means
        /// the OS displayed it, and the brain then acks the reminder; false or an error leaves the
        /// reminder deliverable. The body escapes the text, because a toast template is XML.
        async fn notify(
            &self,
            request: tonic::Request<super::NotifyRequest>,
        ) -> std::result::Result<tonic::Response<super::NotifyReply>, tonic::Status>;
    }
    /// ---
    ///
    /// ## BodyService is hosted by the body. The brain is the client.
    #[derive(Debug)]
    pub struct BodyServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BodyServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BodyServiceServer<T>
    where
        T: BodyService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cortex.seam.v1.BodyService/CaptureScreen" => {
                    #[allow(non_camel_case_types)]
                    struct CaptureScreenSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::CaptureScreenRequest>
                    for CaptureScreenSvc<T> {
                        type Response = super::CaptureScreenReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CaptureScreenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::capture_screen(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CaptureScreenSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/GetVolume" => {
                    #[allow(non_camel_case_types)]
                    struct GetVolumeSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::GetVolumeRequest>
                    for GetVolumeSvc<T> {
                        type Response = super::VolumeState;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetVolumeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::get_volume(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetVolumeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/SetVolume" => {
                    #[allow(non_camel_case_types)]
                    struct SetVolumeSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::SetVolumeRequest>
                    for SetVolumeSvc<T> {
                        type Response = super::VolumeState;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetVolumeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::set_volume(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetVolumeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/InjectInput" => {
                    #[allow(non_camel_case_types)]
                    struct InjectInputSvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::InjectInputRequest>
                    for InjectInputSvc<T> {
                        type Response = super::InjectInputReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InjectInputRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::inject_input(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InjectInputSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cortex.seam.v1.BodyService/Notify" => {
                    #[allow(non_camel_case_types)]
                    struct NotifySvc<T: BodyService>(pub Arc<T>);
                    impl<
                        T: BodyService,
                    > tonic::server::UnaryService<super::NotifyRequest>
                    for NotifySvc<T> {
                        type Response = super::NotifyReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::NotifyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BodyService>::notify(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = NotifySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BodyServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cortex.seam.v1.BodyService";
    impl<T> tonic::server::NamedService for BodyServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
