"""Render the generated half of a backlog index from its task files."""

from backlog import NEEDS_TRIGGER, OPEN_STATES, UNRECORDED, Status, Task

BEGIN = "<!-- backlog:begin (generated by `just backlog`; edit the task files, not this block) -->"
END = "<!-- backlog:end -->"

BUCKET_ORDER = (
    *OPEN_STATES.values(),
    "Never attempted",
    "Attempted, inconclusive",
)
CLOSED_ORDER = ("Done", "Declined", "Satisfied")


def _describe(status: Status) -> str:
    """Return the short status phrase shown in a roll-call line."""
    if status.state in OPEN_STATES:
        return f"open, {status.state}"
    if status.is_ongoing:
        return f"{status.state}: {status.detail}"
    if status.on is None:
        return status.state
    return f"{status.state} {status.on.isoformat()}"


def _ongoing_section(tasks: list[Task]) -> list[str]:
    """Return the ongoing items, which are neither remaining work nor finished."""
    ongoing = sorted(
        (task for task in tasks if task.status.is_ongoing), key=lambda item: item.number
    )
    if not ongoing:
        return []
    lines = [f"## Ongoing, never closes ({len(ongoing)})", ""]
    lines.append(
        "Neither work that remains nor work that finishes: an observation made over time, or an "
        "obligation on every change. They are counted apart so that neither number is wrong."
    )
    lines.append("")
    lines.extend(
        f"- **{_link(task)}** {task.title} ({task.group}): {task.status.detail}."
        for task in ongoing
    )
    lines.append("")
    return lines


def _link(task: Task) -> str:
    """Return the markdown link to ``task``, relative to its index."""
    return f"[{task.ident}](tasks/{task.path.name})"


def _open_section(tasks: list[Task]) -> list[str]:
    """Return the "what remains" half: every open task under its bucket heading."""
    lines: list[str] = []
    for bucket in BUCKET_ORDER:
        in_bucket = [task for task in tasks if task.status.is_open and task.status.bucket == bucket]
        if not in_bucket:
            continue
        lines.append(f"### {bucket} ({len(in_bucket)})")
        lines.append("")
        for task in sorted(in_bucket, key=lambda item: item.number):
            entry = f"- **{_link(task)}** {task.title} ({task.group})."
            trigger = task.fields.get("Trigger")
            if trigger and task.status.state in NEEDS_TRIGGER:
                entry += (
                    " No trigger was ever recorded for it."
                    if trigger == UNRECORDED
                    else f" Reopens when: {trigger.removesuffix('.')}."
                )
            verified = task.fields.get("Verified")
            if verified:
                entry += f" Its claim was checked against the code on {verified}."
            lines.append(entry)
        lines.append("")
    return lines


def _group_section(tasks: list[Task], group_word: str) -> list[str]:
    """Return the roll call: every task, open and closed, under its group heading."""
    lines: list[str] = []
    groups = sorted({task.group for task in tasks})
    for group in groups:
        members = sorted(
            (task for task in tasks if task.group == group), key=lambda item: item.number
        )
        opens = [task for task in members if task.status.is_open]
        lines.append(f"### {group}")
        lines.append("")
        lines.append(f"{len(opens)} open of {len(members)}.")
        lines.append("")
        lines.extend(f"- {_link(task)} {task.title}. {_describe(task.status)}." for task in members)
        lines.append("")
    if not groups:
        lines.append(f"No {group_word} holds a task yet.")
        lines.append("")
    return lines


def _verified_note(read: list[Task]) -> list[str]:
    """Return the paragraph counting the tasks whose claim somebody checked and dated."""
    if not read:
        return []
    opener = (
        "One of these records the day its claim was last checked against the code"
        if len(read) == 1
        else f"{len(read)} of these record the day their claims were last checked against the code"
    )
    return [f"{opener}. On every other task here, that reading is still yours to take.", ""]


def render(tasks: list[Task], group_word: str) -> str:
    """Return the whole generated block for ``tasks``, markers included."""
    opens = [task for task in tasks if task.status.is_open]
    ongoing = [task for task in tasks if task.status.is_ongoing]
    closed = len(tasks) - len(opens) - len(ongoing)
    counted = f"**{len(opens)} open, "
    if ongoing:
        counted += f"{len(ongoing)} ongoing, "
    lines = [BEGIN, "", f"{counted}{closed} closed, {len(tasks)} in total.**", ""]
    lines.append("## What remains")
    lines.append("")
    blank = [
        task
        for task in tasks
        if task.status.state in NEEDS_TRIGGER and task.fields.get("Trigger") == UNRECORDED
    ]
    if blank:
        opener = "One of these waits" if len(blank) == 1 else f"{len(blank)} of these wait"
        lines.append(
            f"{opener} on something nobody wrote down. That is a gap in the "
            f"record rather than a decision, and reading one of them closes it."
        )
        lines.append("")
    lines.extend(_verified_note([task for task in tasks if task.fields.get("Verified")]))
    if opens:
        lines.extend(_open_section(tasks))
    else:
        lines.append("Nothing. Every task here is closed.")
        lines.append("")
    lines.extend(_ongoing_section(tasks))
    lines.append(f"## Every task, by {group_word}")
    lines.append("")
    lines.extend(_group_section(tasks, group_word))
    lines.append(END)
    return "\n".join(lines)


def splice(existing: str, block: str) -> str:
    """Return ``existing`` with its generated block replaced by ``block``."""
    start = existing.find(BEGIN)
    end = existing.find(END)
    if start == -1 or end == -1 or end < start:
        msg = f"the index needs both {BEGIN!r} and {END!r}, in that order"
        raise ValueError(msg)
    return existing[:start] + block + existing[end + len(END) :]
