"""Repo gate: fail when the committed Rust stub stops saying what the proto says.

`proto/body.proto` is the single source of truth for the body/brain seam, and both trees commit the
stubs generated from it, regenerated by hand with `just proto` (ADR-0003). A proto edit followed by
no regeneration leaves the stub stating the old thing with every gate green, because generated code
sits outside every other scan here (ADR-0001 decision 7).

Every comment the proto body carries must still appear as a doc comment in
`body/crates/rpc/src/_generated/cortex.seam.v1.rs`, in as many copies as the stub holds it. Tonic
writes each service into a client module and a server module and documents both from the one
declaration, so a service comment stands there twice, and containment alone would let one of the
two be reworded while the other answered for it. The comparison runs one way only, since the stub
also carries doc comments tonic wrote about its own client and server. It compares text and runs no
codegen, which is what lets it live inside `just check` at all: regenerating the Rust half needs a
system `protoc` binary that `tonic-prost-build` shells out to and a clean dev box need not have.

The ADR-0003 stub-fidelity addendum and `docs/modules/repo-gates.md` argue the rule, the one tally
that is pinned rather than counted, and what this gate does not hold.

A missing or unreadable input, a proto whose header this reader cannot tell from its body, a
comment shape it does not parse, and either side of the comparison coming back empty each fail
rather than passing quietly, because a comparison over an empty collection would report success
forever. The success line states what the comparison was over: the proto comments read, split by
whether each stands on its own line or trails code, how many of them a service claims two copies
of, and the stub doc lines they were sought in.
"""

import argparse
import sys
from collections import Counter
from collections.abc import Iterable
from pathlib import Path
from typing import NamedTuple

from protocomments import (
    COPIES,
    RULE,
    Comment,
    ProtoReadError,
    normalize,
    proto_comments,
    rust_docs,
)

# The two files this gate ties together, relative to the repo root: the source of truth for the
# seam, and the generated half that copies its prose verbatim.
PROTO = Path("proto/body.proto")
STUB = Path("body/crates/rpc/src/_generated/cortex.seam.v1.rs")

# The floor under the reading in the success line: a side that came back empty has read nothing,
# and a comparison over nothing cannot fail.
MIN_COMMENTS = 1
MIN_DOCS = 1


class StubCheckError(Exception):
    """An input could not be read, or one side of the comparison came back empty."""


class Miss(NamedTuple):
    """One proto comment the committed stub carries fewer copies of than it is owed."""

    line: int
    text: str
    wanted: int
    found: int


class Scan(NamedTuple):
    """One comparison: what it was over, then what it could not account for.

    ``leading`` and ``trailing`` are counted apart rather than summed, because they are read by
    different rules and only one of them survives a naive `//` split. ``doubled`` overlaps both
    and answers a third question, how many comments a service claims two copies of. ``docs`` is
    none of them and not derivable from them: the stub says more than the proto does.
    """

    leading: int
    trailing: int
    doubled: int
    docs: int
    misses: list[Miss]


def _read(root: Path, relative: Path) -> str:
    """Read one side of the comparison, raising when the file is absent or is not text."""
    try:
        return (root / relative).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as err:
        msg = f"cannot read {relative.as_posix()}: {err}"
        raise StubCheckError(msg) from err


def owed(comments: Iterable[Comment]) -> Counter[str]:
    """How many copies of each normalized text the stub owes, a service comment owing two.

    A rule line is the one text whose tally is pinned rather than summed, at a floor of one,
    because prost absorbs a banner's closing rule into the heading above it and the copies that
    survive are then not a function of the copies written.
    """
    tally: Counter[str] = Counter()
    for comment in comments:
        text = normalize(comment.text)
        if text == RULE:
            tally[text] = MIN_DOCS
            continue
        tally[text] += COPIES if comment.service else 1
    return tally


def shortfalls(comments: Iterable[Comment], said: Counter[str]) -> list[Miss]:
    """Every text the stub holds fewer copies of than it owes, reported at its first proto line."""
    wanted = owed(comments)
    seen: set[str] = set()
    misses: list[Miss] = []
    for comment in comments:
        text = normalize(comment.text)
        if text in seen or said[text] >= wanted[text]:
            continue
        seen.add(text)
        misses.append(
            Miss(
                line=comment.line,
                text=comment.text.strip(),
                wanted=wanted[text],
                found=said[text],
            )
        )
    return misses


def check(root: Path) -> Scan:
    """Compare every comment in the proto body against the committed stub's doc comments."""
    proto_text = _read(root, PROTO)
    stub_text = _read(root, STUB)
    try:
        comments = proto_comments(proto_text)
    except ProtoReadError as err:
        msg = f"{PROTO.as_posix()}: {err}"
        raise StubCheckError(msg) from err
    docs = rust_docs(stub_text)
    if len(comments) < MIN_COMMENTS:
        msg = f"no comment in {PROTO.as_posix()}; a comparison over nothing cannot fail"
        raise StubCheckError(msg)
    if len(docs) < MIN_DOCS:
        msg = f"no doc comment in {STUB.as_posix()}; a comparison over nothing cannot fail"
        raise StubCheckError(msg)
    return Scan(
        leading=sum(1 for comment in comments if comment.leading),
        trailing=sum(1 for comment in comments if not comment.leading),
        doubled=sum(1 for comment in comments if comment.service),
        docs=len(docs),
        misses=shortfalls(comments, Counter(normalize(doc) for doc in docs)),
    )


def main(argv: list[str] | None = None) -> int:
    """Run the gate; print any misses and return the process exit code."""
    parser = argparse.ArgumentParser(
        description="Fail when a proto comment is missing from the committed Rust stub.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(),
        help="repo root holding the proto and the committed stub (default: current directory)",
    )
    args = parser.parse_args(argv)
    given: Path = args.root
    if not given.is_dir():
        print(f"stubcheck: root {given} is not a directory", file=sys.stderr)
        return 2
    root = given.resolve()
    try:
        scanned = check(root)
    except StubCheckError as err:
        print(f"stubcheck: {err}", file=sys.stderr)
        return 2
    for miss in scanned.misses:
        print(
            f"{PROTO.as_posix()}:{miss.line}: the stub says {miss.text!r} {miss.found} time(s), "
            f"and this comment is owed {miss.wanted}"
        )
    if scanned.misses:
        print(
            f"\nstubcheck: {len(scanned.misses)} proto comment(s) are missing from "
            f"{STUB.as_posix()}, or stand there in fewer copies than it holds; a comment on a "
            "service is written into both the client and the server module. Regenerate the "
            "committed stubs with `just proto` and commit them; a stub nobody regenerated goes "
            "on stating what the proto used to say.",
            file=sys.stderr,
        )
        return 1
    print(
        f"stubcheck OK: {scanned.leading + scanned.trailing} proto comment(s) under {given} "
        f"({scanned.leading} leading, {scanned.trailing} trailing, {scanned.doubled} owed two "
        f"copies) appear in the committed Rust stub, over {scanned.docs} doc line(s) read"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover -- CLI entry point; main() is unit-tested
    sys.exit(main())
