"""Repo gate: fail when the committed Rust stub stops saying what the proto says.

`proto/body.proto` is the single source of truth for the body/brain seam, and both trees commit
the stubs generated from it, regenerated by hand with `just proto` (ADR-0003). Nothing held those
committed stubs to the proto they came from. A proto edit followed by no regeneration leaves the
stub stating the old thing with every gate green, because a stub is generated code and generated
code sits outside every scan here (ADR-0001 decision 7). This is the one thread back.

**The rule.** Every comment the proto body carries must still appear as a doc comment in
`body/crates/rpc/src/_generated/cortex.seam.v1.rs`. It is a text comparison and no codegen runs,
which is what lets it live inside `just check`: regenerating the Rust half needs a system
`protoc` binary that `tonic-prost-build` shells out to and a clean dev box need not have, and a
gate requiring one would make the single gate unrunnable rather than strict.

**One direction only.** The stub carries doc comments the proto never wrote, tonic documenting
its own generated client and server, so the reverse containment is false by construction and
could never be a rule. The direction that matters is this one: what the proto says, the stub must
still say.

**What it does not hold**, which is the honest half of the description:

- It is not a regeneration check. It proves the stub still carries the proto's prose, never that
  running `just proto` today would reproduce the committed bytes.
- It does not see structural drift, and deliberately does not try. A renamed or removed field is
  already loud: `pyright` fails over the Python stub's `.pyi` and the Rust tree stops compiling.
  A field added to the proto and generated for nowhere is a field no code uses yet.
- The Python half of the seam is out of its reach, and adding it would buy nothing. Regenerating
  into a temp directory and diffing was measured, and `grpcio-tools` bundles its own `protoc` so
  it would even fit in the gate, but the Python stubs carry no comments at all: the `.pyi` has
  none and the descriptor in `body_pb2.py` is stripped of its source info, so a comment-only proto
  edit leaves all three generated Python files byte identical.

Which leaves the comment as the one silent case, and it is a real one. The comment on `max_edge`
stating the body's own default longest edge is a registered far side of a cross-language constant
in `crosscheck.py`'s registry; the generated copy of that sentence in the Rust stub is not, and
that copy is the one a Rust reader actually opens. Retune the edge and regenerate, and the stub
follows. Retune it and forget, and the stub goes on stating the old number forever.

**Fail closed**, the way `bindcheck.py` does. A missing or unreadable input, a proto whose header
this reader cannot tell from its body, a comment shape it will not guess at, and either side of
the comparison coming back empty are each a failure rather than a quiet pass, because a
comparison over an empty collection would report success forever.

**The success line states what the comparison was over**: the proto comments read, split by
whether each stands on its own line or trails code, and the stub doc lines they were sought in.
It is a reading and nothing asserts it. The floor under it is the assertion.
"""

import argparse
import sys
from pathlib import Path
from typing import NamedTuple

from protocomments import ProtoReadError, normalize, proto_comments, rust_docs

# The two files this gate ties together, relative to the repo root: the source of truth for the
# seam, and the generated half that copies its prose verbatim.
PROTO = Path("proto/body.proto")
STUB = Path("body/crates/rpc/src/_generated/cortex.seam.v1.rs")

# The floor under the reading in the success line, and the same floor `dashcheck.py` carries: a
# side that came back empty has read nothing, and a comparison over nothing cannot fail.
MIN_COMMENTS = 1
MIN_DOCS = 1


class StubCheckError(Exception):
    """An input could not be read, or one side of the comparison came back empty."""


class Miss(NamedTuple):
    """One proto comment the committed stub no longer carries."""

    line: int
    text: str


class Scan(NamedTuple):
    """One comparison: what it was over, then what it could not account for.

    ``leading`` and ``trailing`` are counted apart rather than summed, because they are read by
    different rules and only one of them survives a naive `//` split. ``docs`` is neither of
    them and not derivable from them: the stub says more than the proto does.
    """

    leading: int
    trailing: int
    docs: int
    misses: list[Miss]


def _read(root: Path, relative: Path) -> str:
    """Read one side of the comparison, refusing a file that is absent or is not text."""
    try:
        return (root / relative).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as err:
        msg = f"cannot read {relative.as_posix()}: {err}"
        raise StubCheckError(msg) from err


def check(root: Path) -> Scan:
    """Compare every comment in the proto body against the committed stub's doc comments."""
    proto_text = _read(root, PROTO)
    stub_text = _read(root, STUB)
    try:
        comments = proto_comments(proto_text)
    except ProtoReadError as err:
        msg = f"{PROTO.as_posix()}: {err}"
        raise StubCheckError(msg) from err
    docs = rust_docs(stub_text)
    if len(comments) < MIN_COMMENTS:
        msg = f"no comment in {PROTO.as_posix()}; a comparison over nothing cannot fail"
        raise StubCheckError(msg)
    if len(docs) < MIN_DOCS:
        msg = f"no doc comment in {STUB.as_posix()}; a comparison over nothing cannot fail"
        raise StubCheckError(msg)
    said = {normalize(doc) for doc in docs}
    return Scan(
        leading=sum(1 for comment in comments if comment.leading),
        trailing=sum(1 for comment in comments if not comment.leading),
        docs=len(docs),
        misses=[
            Miss(line=comment.line, text=comment.text.strip())
            for comment in comments
            if normalize(comment.text) not in said
        ],
    )


def main(argv: list[str] | None = None) -> int:
    """Run the gate; print any misses and return the process exit code."""
    parser = argparse.ArgumentParser(
        description="Fail when a proto comment is missing from the committed Rust stub.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(),
        help="repo root holding the proto and the committed stub (default: current directory)",
    )
    args = parser.parse_args(argv)
    given: Path = args.root
    if not given.is_dir():
        print(f"stubcheck: root {given} is not a directory", file=sys.stderr)
        return 2
    root = given.resolve()
    try:
        scanned = check(root)
    except StubCheckError as err:
        print(f"stubcheck: {err}", file=sys.stderr)
        return 2
    for miss in scanned.misses:
        print(f"{PROTO.as_posix()}:{miss.line}: the stub carries no comment saying {miss.text!r}")
    if scanned.misses:
        print(
            f"\nstubcheck: {len(scanned.misses)} proto comment(s) are missing from "
            f"{STUB.as_posix()}. Regenerate the committed stubs with `just proto` and commit "
            f"them; a stub nobody regenerated goes on stating what the proto used to say.",
            file=sys.stderr,
        )
        return 1
    print(
        f"stubcheck OK: {scanned.leading + scanned.trailing} proto comment(s) under {given} "
        f"({scanned.leading} leading, {scanned.trailing} trailing) appear in the committed Rust "
        f"stub, over {scanned.docs} doc line(s) read"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover -- CLI entry point; main() is unit-tested
    sys.exit(main())
