# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cortex_seam._generated import body_pb2 as cortex__seam_dot___generated_dot_body__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortex_seam/_generated/body_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub:
    """---------------------------------------------------------------------------
    BrainService is hosted by the brain, in Docker. The body is the client.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Converse = channel.stream_stream(
                '/cortex.seam.v1.BrainService/Converse',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.ClientEvent.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.ServerEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cortex.seam.v1.BrainService/Health',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.HealthRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.HealthReply.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/cortex.seam.v1.BrainService/ListSessions',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.ListSessionsReply.FromString,
                _registered_method=True)
        self.GetSessionMessages = channel.unary_unary(
                '/cortex.seam.v1.BrainService/GetSessionMessages',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.GetSessionMessagesRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.GetSessionMessagesReply.FromString,
                _registered_method=True)
        self.ListDueReminders = channel.unary_unary(
                '/cortex.seam.v1.BrainService/ListDueReminders',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.ListDueRemindersRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.ListDueRemindersReply.FromString,
                _registered_method=True)
        self.AckReminder = channel.unary_unary(
                '/cortex.seam.v1.BrainService/AckReminder',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.AckReminderRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.AckReminderReply.FromString,
                _registered_method=True)
        self.RenameSession = channel.unary_unary(
                '/cortex.seam.v1.BrainService/RenameSession',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.RenameSessionRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.RenameSessionReply.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/cortex.seam.v1.BrainService/DeleteSession',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.DeleteSessionReply.FromString,
                _registered_method=True)
        self.SetSessionHoisted = channel.unary_unary(
                '/cortex.seam.v1.BrainService/SetSessionHoisted',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.SetSessionHoistedRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.SetSessionHoistedReply.FromString,
                _registered_method=True)
        self.GetPreferences = channel.unary_unary(
                '/cortex.seam.v1.BrainService/GetPreferences',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.GetPreferencesRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.GetPreferencesReply.FromString,
                _registered_method=True)
        self.SetPreference = channel.unary_unary(
                '/cortex.seam.v1.BrainService/SetPreference',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.SetPreferenceRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.SetPreferenceReply.FromString,
                _registered_method=True)


class BrainServiceServicer:
    """---------------------------------------------------------------------------
    BrainService is hosted by the brain, in Docker. The body is the client.
    ---------------------------------------------------------------------------
    """

    def Converse(self, request_iterator, context):
        """One conversational exchange per overlay session. Client events send user turns and
        cancellations; server events stream tokens, tool activity and status, such as a model
        loading during a handoff.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness and readiness, for the overlay's connection indicator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Read-only views of the session store, for the overlay's chat list and switcher.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDueReminders(self, request, context):
        """Reminder pull delivery: the overlay shows what has fired and is still undelivered, then
        acks what it showed. A brain with no schedule store answers an empty list and acked=false
        rather than an error, because it cannot be told from one with nothing due.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckReminder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameSession(self, request, context):
        """Renames a chat. Reachable only from the overlay's own list controls, never from a model or
        a tool, and it stores a display title only, never conversation content. An empty title
        clears the override, so the title derived from the first message applies again.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Deletes a chat: destructive and irreversible. The transcript, the catalog entry and the
        session's private memories all go. The overlay asks the user to confirm before sending
        this, and the body makes exactly one attempt so a lost reply cannot destroy twice.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSessionHoisted(self, request, context):
        """Hoists or lowers a chat. A hoisted chat is listed whatever its age, above the chats
        listed by recency. Reachable only from the overlay's list controls, and the body
        makes exactly one attempt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreferences(self, request, context):
        """The user's settings: a durable key/value record the brain owns, so a choice survives a body
        restart. Keys are namespaced names the caller owns ("overlay.theme"); values are short
        strings the brain stores and returns without reading them. An empty value clears the key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Converse': grpc.stream_stream_rpc_method_handler(
                    servicer.Converse,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.ClientEvent.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.ServerEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.HealthRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.HealthReply.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.ListSessionsRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.ListSessionsReply.SerializeToString,
            ),
            'GetSessionMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionMessages,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.GetSessionMessagesRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.GetSessionMessagesReply.SerializeToString,
            ),
            'ListDueReminders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDueReminders,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.ListDueRemindersRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.ListDueRemindersReply.SerializeToString,
            ),
            'AckReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.AckReminder,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.AckReminderRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.AckReminderReply.SerializeToString,
            ),
            'RenameSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameSession,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.RenameSessionRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.RenameSessionReply.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.DeleteSessionRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.DeleteSessionReply.SerializeToString,
            ),
            'SetSessionHoisted': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSessionHoisted,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.SetSessionHoistedRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.SetSessionHoistedReply.SerializeToString,
            ),
            'GetPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreferences,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.GetPreferencesRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.GetPreferencesReply.SerializeToString,
            ),
            'SetPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreference,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.SetPreferenceRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.SetPreferenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.seam.v1.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.seam.v1.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService:
    """---------------------------------------------------------------------------
    BrainService is hosted by the brain, in Docker. The body is the client.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Converse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cortex.seam.v1.BrainService/Converse',
            cortex__seam_dot___generated_dot_body__pb2.ClientEvent.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/Health',
            cortex__seam_dot___generated_dot_body__pb2.HealthRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/ListSessions',
            cortex__seam_dot___generated_dot_body__pb2.ListSessionsRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.ListSessionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/GetSessionMessages',
            cortex__seam_dot___generated_dot_body__pb2.GetSessionMessagesRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.GetSessionMessagesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDueReminders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/ListDueReminders',
            cortex__seam_dot___generated_dot_body__pb2.ListDueRemindersRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.ListDueRemindersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/AckReminder',
            cortex__seam_dot___generated_dot_body__pb2.AckReminderRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.AckReminderReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/RenameSession',
            cortex__seam_dot___generated_dot_body__pb2.RenameSessionRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.RenameSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/DeleteSession',
            cortex__seam_dot___generated_dot_body__pb2.DeleteSessionRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.DeleteSessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSessionHoisted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/SetSessionHoisted',
            cortex__seam_dot___generated_dot_body__pb2.SetSessionHoistedRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.SetSessionHoistedReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/GetPreferences',
            cortex__seam_dot___generated_dot_body__pb2.GetPreferencesRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.GetPreferencesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/SetPreference',
            cortex__seam_dot___generated_dot_body__pb2.SetPreferenceRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.SetPreferenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BodyServiceStub:
    """---------------------------------------------------------------------------
    BodyService is hosted by the body. The brain is the client.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureScreen = channel.unary_unary(
                '/cortex.seam.v1.BodyService/CaptureScreen',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenReply.FromString,
                _registered_method=True)
        self.GetVolume = channel.unary_unary(
                '/cortex.seam.v1.BodyService/GetVolume',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.GetVolumeRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
                _registered_method=True)
        self.SetVolume = channel.unary_unary(
                '/cortex.seam.v1.BodyService/SetVolume',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.SetVolumeRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
                _registered_method=True)
        self.InjectInput = channel.unary_unary(
                '/cortex.seam.v1.BodyService/InjectInput',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputReply.FromString,
                _registered_method=True)
        self.Notify = channel.unary_unary(
                '/cortex.seam.v1.BodyService/Notify',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.NotifyRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.NotifyReply.FromString,
                _registered_method=True)


class BodyServiceServicer:
    """---------------------------------------------------------------------------
    BodyService is hosted by the body. The brain is the client.
    ---------------------------------------------------------------------------
    """

    def CaptureScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Shows a native notification, which is the push half of reminder delivery. shown=true means
        the OS displayed it, and the brain then acks the reminder; false or an error leaves the
        reminder deliverable. The body escapes the text, because a toast template is XML.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BodyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreen,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenReply.SerializeToString,
            ),
            'GetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolume,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.GetVolumeRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.SerializeToString,
            ),
            'SetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVolume,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.SetVolumeRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.SerializeToString,
            ),
            'InjectInput': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectInput,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputReply.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.NotifyRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.NotifyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.seam.v1.BodyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.seam.v1.BodyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BodyService:
    """---------------------------------------------------------------------------
    BodyService is hosted by the body. The brain is the client.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def CaptureScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/CaptureScreen',
            cortex__seam_dot___generated_dot_body__pb2.CaptureScreenRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.CaptureScreenReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/GetVolume',
            cortex__seam_dot___generated_dot_body__pb2.GetVolumeRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/SetVolume',
            cortex__seam_dot___generated_dot_body__pb2.SetVolumeRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/InjectInput',
            cortex__seam_dot___generated_dot_body__pb2.InjectInputRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.InjectInputReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/Notify',
            cortex__seam_dot___generated_dot_body__pb2.NotifyRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.NotifyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
