# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cortex_seam._generated import body_pb2 as cortex__seam_dot___generated_dot_body__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortex_seam/_generated/body_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub:
    """---------------------------------------------------------------------------
    BrainService is hosted by the brain (Docker). The body is the client.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Converse = channel.stream_stream(
                '/cortex.seam.v1.BrainService/Converse',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.ClientEvent.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.ServerEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cortex.seam.v1.BrainService/Health',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.HealthRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.HealthReply.FromString,
                _registered_method=True)


class BrainServiceServicer:
    """---------------------------------------------------------------------------
    BrainService is hosted by the brain (Docker). The body is the client.
    ---------------------------------------------------------------------------
    """

    def Converse(self, request_iterator, context):
        """One conversational exchange stream per overlay session. Client events carry user
        turns and cancellations; server events stream tokens, tool activity, and status
        (e.g. "brain model loading" during a handoff, so the overlay can show progress).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness/readiness for the overlay to display connection state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Converse': grpc.stream_stream_rpc_method_handler(
                    servicer.Converse,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.ClientEvent.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.ServerEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.HealthRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.seam.v1.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.seam.v1.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService:
    """---------------------------------------------------------------------------
    BrainService is hosted by the brain (Docker). The body is the client.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Converse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cortex.seam.v1.BrainService/Converse',
            cortex__seam_dot___generated_dot_body__pb2.ClientEvent.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BrainService/Health',
            cortex__seam_dot___generated_dot_body__pb2.HealthRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BodyServiceStub:
    """---------------------------------------------------------------------------
    BodyService is hosted by the body (host-native). The brain is the client.
    Exposes host OS capabilities behind the body's Rust traits.
    (Whether these also surface to models as MCP tools: ADR-0001 open question #2.
    Connectivity direction: ADR-0001 open question #3.)
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureScreen = channel.unary_unary(
                '/cortex.seam.v1.BodyService/CaptureScreen',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenReply.FromString,
                _registered_method=True)
        self.GetVolume = channel.unary_unary(
                '/cortex.seam.v1.BodyService/GetVolume',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.GetVolumeRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
                _registered_method=True)
        self.SetVolume = channel.unary_unary(
                '/cortex.seam.v1.BodyService/SetVolume',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.SetVolumeRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
                _registered_method=True)
        self.InjectInput = channel.unary_unary(
                '/cortex.seam.v1.BodyService/InjectInput',
                request_serializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputRequest.SerializeToString,
                response_deserializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputReply.FromString,
                _registered_method=True)


class BodyServiceServicer:
    """---------------------------------------------------------------------------
    BodyService is hosted by the body (host-native). The brain is the client.
    Exposes host OS capabilities behind the body's Rust traits.
    (Whether these also surface to models as MCP tools: ADR-0001 open question #2.
    Connectivity direction: ADR-0001 open question #3.)
    ---------------------------------------------------------------------------
    """

    def CaptureScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVolume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BodyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreen,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.CaptureScreenReply.SerializeToString,
            ),
            'GetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolume,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.GetVolumeRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.SerializeToString,
            ),
            'SetVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVolume,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.SetVolumeRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.VolumeState.SerializeToString,
            ),
            'InjectInput': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectInput,
                    request_deserializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputRequest.FromString,
                    response_serializer=cortex__seam_dot___generated_dot_body__pb2.InjectInputReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.seam.v1.BodyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.seam.v1.BodyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BodyService:
    """---------------------------------------------------------------------------
    BodyService is hosted by the body (host-native). The brain is the client.
    Exposes host OS capabilities behind the body's Rust traits.
    (Whether these also surface to models as MCP tools: ADR-0001 open question #2.
    Connectivity direction: ADR-0001 open question #3.)
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def CaptureScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/CaptureScreen',
            cortex__seam_dot___generated_dot_body__pb2.CaptureScreenRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.CaptureScreenReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/GetVolume',
            cortex__seam_dot___generated_dot_body__pb2.GetVolumeRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/SetVolume',
            cortex__seam_dot___generated_dot_body__pb2.SetVolumeRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.VolumeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.seam.v1.BodyService/InjectInput',
            cortex__seam_dot___generated_dot_body__pb2.InjectInputRequest.SerializeToString,
            cortex__seam_dot___generated_dot_body__pb2.InjectInputReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
